services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sleep infinity
    working_dir: /workspaces
    volumes:
      - ..:/workspaces/file-storage-s3-typescript:cached,Z
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: file-storage
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
