services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sleep infinity
    working_dir: /workspaces
    volumes:
      - ..:/workspaces/file-storage-s3-typescript:cached,Z
